# Generated by Django 4.2.5 on 2023-09-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0001_initial'),
        ('app_tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PayNumber', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending')),
                ('Amount', models.FloatField()),
                ('cusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=50)),
                ('Seat', models.TextField()),
                ('Room', models.TextField()),
                ('BookTime', models.DateTimeField(auto_now_add=True)),
                ('PayNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_general.payment')),
                ('TourName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tours.tours')),
                ('cusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.customer')),
            ],
        ),
    ]
