# Generated by Django 4.2.5 on 2023-09-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookID', models.IntegerField(max_length=5)),
                ('Seat', models.TextField()),
                ('Day', models.DateField()),
                ('TourName', models.CharField(max_length=25)),
                ('AccomName', models.CharField(max_length=25)),
                ('Room', models.TextField()),
                ('AirlineName', models.IntegerField(max_length=5)),
                ('GuideName', models.CharField(max_length=25)),
            ],
        ),
    ]
