# Generated by Django 4.2.5 on 2023-09-06 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tours', '0002_countrys_remove_tournames_id_and_more'),
        ('app_employee', '0001_initial'),
        ('app_general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='AccomName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tours.accommodation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='BookID',
            field=models.IntegerField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='GuideName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_employee.guidetour'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='TourName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tours.tournames'),
        ),
    ]
