# Generated by Django 4.2.5 on 2023-09-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0002_payment_bookid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bookId',
        ),
    ]
