# Generated by Django 4.2.5 on 2023-09-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_remove_customer_bookid_alter_customer_cusid'),
        ('app_general', '0002_remove_booking_id_alter_booking_accomname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cusID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_user.customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='AirlineName',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='booking',
            name='BookID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
