# Generated by Django 4.2.5 on 2023-09-15 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0003_remove_payment_bookid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payNum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_general.payment'),
        ),
    ]
