# Generated by Django 4.2.5 on 2023-09-09 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_remove_customer_bookid_alter_customer_cusid'),
        ('app_general', '0003_booking_cusid_alter_booking_airlinename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cusID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.customer'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PayNumber', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('Amount', models.IntegerField()),
                ('cusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.customer')),
            ],
        ),
    ]
