# Generated by Django 4.2.5 on 2023-09-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guidetour',
            old_name='GuideTour',
            new_name='GuideName',
        ),
        migrations.AlterField(
            model_name='employees',
            name='EmpID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
