# Generated by Django 4.2.5 on 2023-09-19 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CusID', models.AutoField(primary_key=True, serialize=False)),
                ('CusFirstName', models.CharField(max_length=25)),
                ('CusLastName', models.CharField(max_length=25)),
                ('CusContract', models.CharField(max_length=10)),
                ('CusEmail', models.EmailField(max_length=25, unique=True)),
                ('Credits', models.FloatField(default=99999999)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
