# Generated by Django 4.2.5 on 2023-09-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='BookID',
        ),
        migrations.AlterField(
            model_name='customer',
            name='CusID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
