# Generated by Django 4.2.5 on 2023-09-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Credits',
            field=models.FloatField(default=0),
        ),
    ]
