# Generated by Django 4.2.5 on 2023-09-12 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countrys',
            fields=[
                ('CountryID', models.AutoField(primary_key=True, serialize=False)),
                ('CountryName', models.CharField(max_length=15)),
                ('Region', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('LocationName', models.CharField(default='thai', max_length=25, primary_key=True, serialize=False)),
                ('CountryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tours.countrys')),
            ],
        ),
        migrations.CreateModel(
            name='TourNames',
            fields=[
                ('TourName', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Status', models.TextField(choices=[('open', 'Open'), ('close', 'Close')], default='open')),
                ('TripDuration', models.TextField()),
                ('CountryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tours.countrys')),
                ('LocationName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tours.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('AccomName', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('TypeRoom', models.TextField()),
                ('CountryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tours.countrys')),
                ('LocationName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tours.locations')),
            ],
        ),
    ]
