# Generated by Django 4.2.5 on 2023-09-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TourName', models.CharField(max_length=25)),
                ('Status', models.TextField()),
                ('TripDuration', models.TextField()),
                ('LocationID', models.IntegerField(max_length=5)),
                ('CountryID', models.IntegerField(max_length=5)),
            ],
        ),
    ]
