# Generated by Django 4.2.5 on 2023-09-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='LocationName',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tours',
            name='Status',
            field=models.TextField(choices=[('เปิด', 'เปิด'), ('ปิด', 'ปิด'), ('เต็ม', 'เต็ม')], default='open'),
        ),
    ]
