# Generated by Django 4.2.4 on 2023-09-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailTour',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Tour', models.CharField(max_length=25)),
                ('Detail', models.TextField()),
                ('immage', models.ImageField(upload_to='')),
            ],
        ),
    ]
