# Generated by Django 4.2.5 on 2023-09-06 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countrys',
            fields=[
                ('CountryID', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('CountryName', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='tournames',
            name='id',
        ),
        migrations.AlterField(
            model_name='tournames',
            name='TourName',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('LocationID', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('City', models.CharField(max_length=25)),
                ('CountryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tours.countrys')),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('AccomName', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('City', models.CharField(max_length=25)),
                ('TypeRoom', models.TextField()),
                ('CountryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tours.countrys')),
            ],
        ),
        migrations.AlterField(
            model_name='tournames',
            name='CountryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tours.countrys'),
        ),
        migrations.AlterField(
            model_name='tournames',
            name='LocationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tours.locations'),
        ),
    ]
