# Generated by Django 4.2.5 on 2023-09-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tours', '0002_countrys_remove_tournames_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrys',
            name='CountryID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='locations',
            name='LocationID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
