# Generated by Django 4.2.4 on 2023-09-26 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tours', '0002_detailtour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtour',
            name='Tour',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_tours.tours'),
        ),
        migrations.AlterField(
            model_name='detailtour',
            name='immage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
