# Generated by Django 4.2.5 on 2023-09-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tours', '0002_alter_locations_locationname_alter_tours_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='CountryID',
            new_name='CountryName',
        ),
    ]
