# Generated by Django 4.2.5 on 2023-09-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tours', '0003_alter_countrys_countryid_alter_locations_locationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='CountryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tours.countrys'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='CountryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tours.countrys'),
        ),
        migrations.AlterField(
            model_name='tournames',
            name='CountryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tours.countrys'),
        ),
        migrations.AlterField(
            model_name='tournames',
            name='LocationID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tours.locations'),
        ),
    ]
