# Generated by Django 4.2.4 on 2023-09-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tours', '0004_alter_detailtour_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='Detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tours',
            name='immage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='detailTour',
        ),
    ]
