# Generated by Django 4.2.5 on 2023-10-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tours', '0005_tours_detail_tours_immage_delete_detailtour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='immage',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=''),
        ),
    ]
