# Generated by Django 4.2.5 on 2023-10-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tours', '0010_alter_tours_immage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='immage',
            field=models.ImageField(blank=True, default=' ', null=True, upload_to=''),
        ),
    ]
